# Generated by Django 5.1 on 2024-08-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_options_blog_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('free', '자유'), ('travel', '여행'), ('food', '음식'), ('game', '게임')], default='free', max_length=15, verbose_name='카테고리'),
        ),
    ]
